<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php 
$baseUrl = Mage::getUrl('*/*/submitPost');
echo $baseUrl;
?>
        <form action="<?php echo $baseUrl; ?>" method="post">
            <fieldset>
                <legend>Post Form</legend>
                <label>Post Title: </label>
                <input type="text" name="title" />
                <label>Post Description: </label>
                <input type="text" name="description" />
                <input type="submit" value="Post" />
            </fieldset>
        </form>
