<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php $baseUrl = Mage::getUrl('*/*/submit'); 
$postId = $this->getRequest()->getParam('post_id');
?>
<form action ="<?php echo $baseUrl; ?>" method="post">
    <label>Title: </label>
    <input type="text" name="title" />
    <label>Description: </label>
    <textarea name="description"></textarea>
    <input type="hidden" name="post_id" value="<?php echo $postId ?>" />
    <input type="hidden" name="form-type" value="comment" />
    <input type="submit" value="Post Comment" />
</form>